### PR TITLE
Generate visualizations of the graph

### PR DESCRIPTION
**Pull request by muelldlr**
Generate visualization of a given GraphCreator with his Collections and Edgedefinitions. It's implemented as a cli command `cag visualize <Path to file>`.

### CODE REVIEW

**Comment by muelldlr** [comment]
Found an issue. Will fix it.

**Comment by roxanneelbaff** [comment]
hey this is closed with unmerged commits

**Comment by muelldlr** [comment]
> hey this is closed with unmerged commits
I messed up, this branch somehow... Please take a look at #24. After that is sorted out, I will fix this.

**Comment by muelldlr** [comment]
Reopened this PR, will fix issues on this Branch after #24 has been discussed.

**Comment by roxanneelbaff** [comment]
All good but why are naming test, test24 ? I would avoid numerical naming

**Pull request closed without merging**
